CREATE OR REPLACE PROCEDURE ICCD.SP_GET_ALL_COUNTRY(
    p_country_name IN VARCHAR2,
    o_country_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN o_country_cursor FOR
    SELECT 
COUNTRYID, COUNTRYNAME
FROM ICCD.TBL_COUNTRY;

END SP_GET_ALL_COUNTRY;
/